// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.KnownProject | null>}
 */
export function AddProject() {
    return $Call.ByID(1457070117).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectWithStatus[]>}
 */
export function ListProjects() {
    return $Call.ByID(3065454423).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(projectPath) {
    return $Call.ByID(4127192162, projectPath);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function StartServer(projectPath) {
    return $Call.ByID(2016819064, projectPath);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function StopServer(projectPath) {
    return $Call.ByID(3690689294, projectPath);
}

// Private type creation functions
const $$createType0 = $models.KnownProject.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProjectWithStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
