// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KnownProject {
    /**
     * Creates a new KnownProject instance.
     * @param {Partial<KnownProject>} [$$source = {}] - The source object to create the KnownProject.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnownProject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnownProject(/** @type {Partial<KnownProject>} */($$parsedSource));
    }
}

export class ProjectWithStatus {
    /**
     * Creates a new ProjectWithStatus instance.
     * @param {Partial<ProjectWithStatus>} [$$source = {}] - The source object to create the ProjectWithStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWithStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectWithStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWithStatus(/** @type {Partial<ProjectWithStatus>} */($$parsedSource));
    }
}
