// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentServer() {
    return $Call.ByID(1238833064);
}

/**
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function SelectServer(port) {
    return $Call.ByID(2665232865, port);
}
