version: '3'

vars:
  APP_NAME: oraculo-desktop
  BIN_DIR: bin
  FRONTEND_DIR: ../frontend

tasks:
  build:frontend:
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - bun install
      - bun run build
      - rm -rf ../desktop/frontend/dist
      - mkdir -p ../desktop/frontend/dist
      - cp -r out/* ../desktop/frontend/dist/

  build:
    deps: [build:frontend]
    cmds:
      - go build -tags production -trimpath -ldflags="-w -s" -o {{.BIN_DIR}}/{{.APP_NAME}}

  dev:
    cmds:
      - wails3 dev

  generate:
    cmds:
      - wails3 generate bindings
